# Generated by Django 5.2.6 on 2025-09-10 16:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=50)),
                ('typedescription', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'AddressType',
            },
        ),
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deductiontype', models.CharField(max_length=60)),
                ('deductionamount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Deductions',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentname', models.CharField(max_length=50)),
                ('departmentdesc', models.CharField(default='Dept. Desc to be determined', max_length=150)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('fromdate', models.DateField(blank=True, null=True)),
                ('todate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'EmployeePosition',
            },
        ),
        migrations.CreateModel(
            name='PayrollMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payrollmonth', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'PayrollMonth',
            },
        ),
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('postalcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('addresstype', models.ForeignKey(db_column='AddressTypeID', on_delete=django.db.models.deletion.CASCADE, to='payroll.addresstype')),
            ],
            options={
                'db_table': 'AddressInfo',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=70)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Other')], max_length=1)),
                ('hiredate', models.DateField(blank=True, null=True)),
                ('lastupdated', models.DateField()),
                ('addressinfo', models.ForeignKey(blank=True, db_column='AddressInfoID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.addressinfo')),
                ('department', models.ForeignKey(blank=True, db_column='DepartmentID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.department')),
                ('manageremployee', models.ForeignKey(blank=True, db_column='ManagerEmployeeID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.employee')),
                ('employeeposition', models.ForeignKey(blank=True, db_column='EmployeePositionID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.employeeposition')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefitplan', models.CharField(max_length=60)),
                ('employee', models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
            options={
                'db_table': 'Benefits',
            },
        ),
        migrations.CreateModel(
            name='BankInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankinstitution', models.CharField(max_length=100)),
                ('institutionnumber', models.CharField(max_length=3)),
                ('accountnumber', models.CharField(max_length=10)),
                ('transitnumber', models.CharField(max_length=5)),
                ('employee', models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
            options={
                'db_table': 'BankInformation',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressinfo', models.ForeignKey(db_column='AddressInfoID', on_delete=django.db.models.deletion.CASCADE, to='payroll.addressinfo')),
                ('employee', models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
            options={
                'db_table': 'EmployeeAddress',
            },
        ),
        migrations.CreateModel(
            name='HourlyEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField(blank=True, null=True)),
                ('hourlyrate', models.FloatField()),
                ('deduction', models.ForeignKey(db_column='DeductionID', on_delete=django.db.models.deletion.CASCADE, to='payroll.deductions')),
                ('employee', models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
                ('payrollmonth', models.ForeignKey(db_column='PayrollMonthID', on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollmonth')),
            ],
            options={
                'db_table': 'HourlyEmployee',
            },
        ),
        migrations.CreateModel(
            name='HoursWorked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daysworked', models.IntegerField(blank=True, null=True)),
                ('hoursworked', models.FloatField(blank=True, null=True)),
                ('overtimehours', models.FloatField(blank=True, null=True)),
                ('payrollmonth', models.ForeignKey(db_column='PayrollMonthID', on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollmonth')),
            ],
            options={
                'db_table': 'HoursWorked',
            },
        ),
        migrations.CreateModel(
            name='PersonalDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdtype', models.CharField(max_length=60)),
                ('paid', models.BooleanField()),
                ('daysoff', models.FloatField()),
                ('employee', models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
            options={
                'db_table': 'PersonalDays',
            },
        ),
        migrations.CreateModel(
            name='SalariedEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField(blank=True, null=True)),
                ('salaryamount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bonusamount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('deduction', models.ForeignKey(db_column='DeductionID', on_delete=django.db.models.deletion.CASCADE, to='payroll.deductions')),
                ('employee', models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
            options={
                'db_table': 'SalariedEmployee',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtimepay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deductions', models.ForeignKey(db_column='DeductionsID', on_delete=django.db.models.deletion.CASCADE, to='payroll.deductions')),
                ('employee', models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
                ('hourlyemployee', models.ForeignKey(blank=True, db_column='HourlyEmployeeID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.hourlyemployee')),
                ('payrollmonth', models.ForeignKey(db_column='PayrollMonthID', on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollmonth')),
                ('salariedemployee', models.ForeignKey(blank=True, db_column='SalariedEmployeeID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.salariedemployee')),
            ],
            options={
                'db_table': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clockin', models.TimeField(blank=True, null=True)),
                ('clockout', models.TimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
            options={
                'db_table': 'TimeSheet',
            },
        ),
    ]
